name: check code formatting

on:
    push:
        branches: [master, v1.x]
    pull_request:
        branches: [master, v1.x]

jobs:
    check_formatting:
        uses: nRF24/.github/.github/workflows/cpp_lint.yaml@main
        with:
          ignore: examples/old_backups|utility/RPi/bcm2835.h|utility/RPi/bcm2835.c
          extensions: ino,c,cpp,h
